---
format: html
editor: visual
---

## Expectations Overview

At the end of the program, you will present your work at a symposium, which will include both a presentation with slides and a poster session. Each afternoon group will have 25 minutes to present their slide deck, followed by 5 minutes for questions. This gives you approximately 4 slides to introduce the overall topic of pneumococcal disease modeling, and 7 slides for each subgroup to summarize their version of this subject. The poster session will last 45 minutes.

::: callout-important
During the poster session, at least one member of your group should be stationed at the poster at all times, while the other two can explore the room. We expect that you will switch every 15 minutes so that everyone spends at least 15 minutes at the poster and the remaining 30 minutes exploring other projects.
:::

To help you stay on track with compiling your materials, we have prepared the following scheduled assignments. Over the coming weeks, we will guide you through preparing the materials for this symposium and aim to expose you to the process of developing these materials in a professional environment.

When working on a research team, it is expected that you can clearly articulate your research to people outside your specific area of expertise and provide meaningful, constructive feedback to help teammates improve their research. At some companies, to be considered for a promotion, you will be required to present an annual summary of our research and a literature review to the group/department, as well as regularly provide insightful comments and constructive criticisms to colleagues.

This is an ambitious schedule, and we acknowledge the extensive workload you each have during the program. It is equally important for you to experience the research project process as it is to execute the techniques we will teach you to support your project hypothesis/research question. You will not be expected to conduct additional analyses beyond the content we provide and assign.

If you encounter insurmountable difficulties implementing any part of the study, please prioritize completing the overall study over finishing any single part that proves too challenging. We are here to answer any questions you might have and help troubleshoot any implementation problems.

## Format

Each Thursday, you will be expected to have completed specific aspects of your analysis to allow time to process the upcoming material. Additionally, each group will present summaries of their work. The specifics of these expectations are outlined below for each week.

::: callout-important
Time around 1 minute of discussion for each slide. If you need pointers on how to effectively present your work, please check out our tips provided in the [Project Materials](Materials/Materials.qmd) page.
:::

We expect the audience to provide insightful, constructive feedback to help improve and compliment the presenting groups on their work. Additionally, we expect you to foster a positive, collaborative environment within your group, allowing everyone the opportunity to participate meaningfully.

It is critical that each member of your group equally shares the responsibilities of conducting the research and presenting the weekly updates. Complimenting colleagues' work demonstrates good professionalism and helps the team identify and maintain effective practices.

## Thursday, July 3$^{rd}$

**Have Completed:**

-   Conducted a literature search for peer-reviewed references (at least 5 relevant papers), focusing on publications from the last 5-10 years.
-   Any exploratory data analysis (EDA) of your dataset, with simple visualization of the variables (i.e. histograms of variables, etc.).
-   Prepared a background outline.
-   Developed a hypothesis/research question.

**Present (12-15 slides):**

-   1 slide describing your hypothesis/research question. Try to explain how you hope the techniques learned thus far will help you justify any conclusion about this hypothesis/research question.
-   "Journal Club" like presentation where you will include:
    -   5-6 slides, with each slide providing a high-level overview of one peer-reviewed reference. Cover 5-6 of your references. For each paper, briefly explain what the paper is about, methods, if it applies any of the techniques we will be learning, and how it will help you with your study.
    -   3 slides giving a deeper dive into one paper.
-   In less than 3-5 slides, summarize your EDA findings, like:
    -   Time-span it covers, categories (i.e. age groups or regions), number of unique data points, etc.
    -   Briefly discuss the variables, especially if the variables imply features that are not readily obvious.
    -   Discuss any potential gaps or pitfalls found with the data, such as data collection limitations, missing data, or combined outcomes that could confound the observations.

## Thursday, July 10$^{th}$

**Have Completed:**

-   Implemented Time Series and Hierarchical Modeling, focusing on how they support your hypothesis/research questions.
-   Started on methods-specific visualizations and drafting the methods report.

**Present (7-9 slides):**

-   3-5 slides summarizing current results and any conclusions you might have with visualizations and any interesting/unexpected findings.
-   3 slides explaining what Time Series and Hierarchical Modeling are addressing in layman's terms and how they support your hypothesis/study question.
-   1 slide to discuss whether working with the data and seeing the results has shaped the research question/hypothesis.

## Thursday, July 17$^{th}$

**Have Completed:**

-   Implement Market Basket analysis and visualize the results from the GPS pipeline, focusing on how they support your hypothesis/research questions. The subset of your data that is relevant to your research question will be prerun for you using the GPS analysis pipeline, leaving only the visualization tasks for you to complete.
-   Finished the methods section with GPS and Market Basket analysis and relevant visualizations.
-   Slide deck first draft for the 25 minute symposium presentation.
-   Poster first draft.

**Present (4 slides):**

-   1 slide summarizing current results and any conclusions you might have with visualizations and any interesting/unexpected findings.
-   2 slides explaining what GPS and Market Basket are addressing in layman's terms and how they support your hypothesis/study question.
-   1 slide to discuss whether working with the data and seeing the results has shaped the research question/hypothesis.

**Mock Symposium:**

After a brief catch-up on the group's progress, we aim to spend most of the day practicing the presentations and poster sessions. This time is intended to help you practice with peers who understand the type of study you conducted and give you an opportunity to implement any last-minute changes to improve your content.

On the symposium day, each afternoon group will be given 25 minutes to present their slides followed by 5-10 minutes of peer-feedback. For the audience, provide feedback about:

-   Whether the presentation was cohesive from start to finish and told a "story" about the study.
-   Highlighted interesting findings unique to their data and hypothesis/research question.
-   If presenters clearly explained the takeaway from each slide and equally shared the responsibilities of presenting.
-   Whether the group explained any shortcomings in their analysis, such as limitations imposed by the dataset's original data collection methods.
-   Whether the slides were light on text and effectively used visuals to communicate the core takeaways from each slide.
-   Whether the presentation formatting was consistent enough to make the progression of information easy to follow. For example, ensuring serotypes are color-coded the same way in each figure.

You will then be mixed into groups of three people with one representative from each group. Each person will be given time to pull up their groups poster on their computer and give a 30 second to 1 minute elevator speech, or "hook". Then explain some of the more detailed highlights you might provide someone who stops at your poster to hear more.

For poster visiters, practice asking questions from the perspective of someone from another project group. Provide feedback about:

-   If the primary 30-second to 1-minute "hook" is engaging and covers relevant points that encompass the study's purpose and findings.
-   How easy it is to understand the project goals and conclusions if you have not conducted a similar study.
-   The effectiveness of the visualizations.
-   Whether the poster is easy for casual browsers to understand, or if it requires a lot of focus to comprehend.

## Monday, July 21$^{st}$

**Have Completed:**

-   Submit the final draft of your poster by 12:00 PM for printing. Upload the `*.potx` into [BDSY 2025 Poster](https://yaleedu.sharepoint.com/sites/BDSY2025Cohort/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=PydphV&CID=cbbb39a0%2Dffde%2D4748%2Db3be%2Db5d3f5867e22&FolderCTID=0x012000674E21BAC282AA44B4D290C0E45388A0&id=%2Fsites%2FBDSY2025Cohort%2FShared%20Documents%2FGeneral%2FBDSY%202025%20Posters) SharePoint folder.

## Tuesday, July 22$^{nd}$

A presentation rehearsal before Professor Mukherjee, all BDSY participants, and project mentors will be held in Winslow Auditorium in Yale School of Public Health's (YSPH) Laboratory of Epidemiology and Public Health (LEPH) building from 2:00 PM to 5:00 PM.

**Have Completed:**

-   Submit the current draft of your slide deck that you wish to present at the rehearsal by 1:30 PM. Upload the `*.pptx` into [BDSY 2025 Presentations](https://yaleedu.sharepoint.com/sites/BDSY2025Cohort/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=7DASbl&CID=b1fd5b91%2D6258%2D4798%2Da665%2Dce52ef8ef87c&FolderCTID=0x012000674E21BAC282AA44B4D290C0E45388A0&id=%2Fsites%2FBDSY2025Cohort%2FShared%20Documents%2FGeneral%2FBDSY%202025%20Presentations) SharePoint folder.

## Wednesday, July 23$^{rd}$

From 6:00 PM to 7:00 PM **every member of your group** will need to drop by the Foundations of Data Science (13th floor, Kline Tower) to pick up your poster. You will also be given the opportunity to get familiar with the symposium space.

**Have Completed:**

-   Submit the final draft of your slide deck by end of day (EOD), 5:00 PM. Upload the `*.pptx` into BDSY 2025 Final Presentations SharePoint folder.

## Thursday, July 24$^{th}$ - Symposium Day!

Arrive at the Foundations of Data Science (13th floor, Kline Tower) at 8:45 AM to prepare for the day. The symposium starts at 9:00 AM.

The poster session will be held in Room 1307 from 1:00 PM to 1:45 PM following lunch (which will be provided). The three afternoon groups will then each have 25 minutes for their presentations from 1:45 PM to 3:00 PM in Room 1327, followed by 5 minutes for questions.

::: callout-important
Dress professionally or in business casual attire. Guests you are inviting—they must RSVP by Monday, July 14$^{th}$.
:::
